In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

### First load the data and make some data cleaning and convert the lables into numerical values

In [2]:
df = pd.read_table("final/processed_squamous_done.txt", sep=" ")
df = df.replace({"Normal": 0, "tumor": 1})
df

ABCA4  ABCB4  ABCC2  ACSL6  ACTL8  ADAMTS18  ADAMTS6  ADAMTS8  \
0      177     89    101    122      1        26      674     8241   
1      187     38     69     66      0       220       46     2092   
2      326    688    118    292      1        16      233     1189   
3       56      9     36     39      0         7      109     4978   
4      125     44     58     85      1         5      206     8034   
5       90     52     76     81      0         6      249     2245   
6       98     25     62     54      0         3       84     3356   
7       57     29     79     53      0        20      109     3283   
8      107     16     48     33      0         1       78     2407   
9      316     39     29     58      0         9       53     5510   
10     170     35    101     74      0        37      121     5380   
11     132     16     62     63      0         0       74      984   
12      92     41     38     87      0        24       71     2523   
13     271     53     43    132      0        74      103     3484   
14     149     40     60     98      0       106      130     1469   
15      51     22     40     66      0         5       71     1737   
16     153     74     37    133      0        14       76     1422   
17      75    111     35     96      0         7      170     3269   
18     124     30     72    151      1         5       57     4945   
19      79     30     64     83      0        36      176     1863   
20     139     29     32     94      0       127       89     6547   
21     294     32     48    171      1        18      143     1612   
22      68     32     19    183      0         4       65     4029   
23     264     62     52    119      0         8      173    10575   
24      43     15     38     88      0         3       67     2684   
25     224     33     25    115      0         6       58     4011   
26      78     41     40    113      0        11       88     7513   
27     258     73     30    105      1        23      102     2985   
28      87     27     62     82      0         8      175     4783   
29     344     72     59    144      0        16       86     7111   
..     ...    ...    ...    ...    ...       ...      ...      ...   
521     99     14    206    101    222        10       84       84   
522    472     29     33      0    132         0        9       14   
523    526     11    535     52    145        15       26       43   
524   1628     22     65    135     11        28       74      135   
525    208      6     37     62     11        58        9       10   
526    100     43    377     11      2        51       86       33   
527     96     39     43     11      1        26       53       31   
528    281    108   3989     21     15       156      107      162   
529    138     37     80     89      0        10      157     5145   
530      6     10     14     65      5         9       38        6   
531   4491     27    212    517     59       145       52       95   
532    169    118     28     33      0       816       71      198   
533     79     34     50     34      9       362      123       67   
534    315     38     48     52      0        22       61      121   
535     53     54    189     36     11         7       65       32   
536      4      4     23     16     60        44       34       14   
537     29     33     33     61     20         9       30       88   
538      9     14     53      6      1         2       13       10   
539     79     36     27    492      3        14      129       60   
540     74     34     39    114    112        39      154      221   
541  21286     35    710     50     37        19       11        7   
542     14    158   2578     26      4        93       49       15   
543   3132     22  10303     99     13         5       50       13   
544   2377     33     60     20     88       114       32       23   
545     54     54     35      4      5        69      198       40   
546  26336     

### Dividing the data into attributes and labels

In [3]:
y = df.label
X = df.drop('label', axis=1)

### Dividing the data into training and testing

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=0)

### Since the data has a wide variance of values so scaling the data will be much more powerful for prediction

In [5]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Training the data using random forest classifier which has the number of estimator that defines the number of trees

In [6]:
regressor = RandomForestClassifier(n_estimators=20, random_state=0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

### calculate the accuracy of the model using cofusion matrix and accuracy score

In [7]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[ 21   0]
 [  1 199]]
              precision    recall  f1-score   support

           0       0.95      1.00      0.98        21
           1       1.00      0.99      1.00       200

    accuracy                           1.00       221
   macro avg       0.98      1.00      0.99       221
weighted avg       1.00      1.00      1.00       221

0.995475113122172


### trying with different estimator 

In [8]:
regressor = RandomForestClassifier(n_estimators=5, random_state=0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[ 20   1]
 [  0 200]]
              precision    recall  f1-score   support

           0       1.00      0.95      0.98        21
           1       1.00      1.00      1.00       200

    accuracy                           1.00       221
   macro avg       1.00      0.98      0.99       221
weighted avg       1.00      1.00      1.00       221

0.995475113122172


### trying with different estimator 

In [9]:
regressor = RandomForestClassifier(n_estimators=10, random_state=0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[ 21   0]
 [  1 199]]
              precision    recall  f1-score   support

           0       0.95      1.00      0.98        21
           1       1.00      0.99      1.00       200

    accuracy                           1.00       221
   macro avg       0.98      1.00      0.99       221
weighted avg       1.00      1.00      1.00       221

0.995475113122172


#### so changing the number of estimators didn't change the results

In [10]:
regressor.n_outputs_

1